# Generated by Django 3.0.7 on 2020-09-01 19:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0011_merge_20200824_2339'),
        ('objects', '0011_auto_20200730_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=False)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('headline', models.CharField(max_length=128)),
                ('slug', models.SlugField()),
                ('members_only', models.BooleanField(default=True)),
                ('text', models.TextField(max_length=65535)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=155, null=True)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.Code')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.Image')),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.Link')),
                ('marshmallows', models.ManyToManyField(blank=True, to='members.Marshmallow')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Member')),
                ('re', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Post')),
                ('sound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.Sound')),
                ('tags', models.ManyToManyField(blank=True, to='objects.Tag')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.Video')),
            ],
            options={
                'ordering': ['-publication_date', '-creation_date'],
            },
        ),
    ]
