# Generated by Django 3.0.7 on 2020-09-01 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='headline',
            new_name='title',
        ),
    ]
