# Generated by Django 3.1.7 on 2021-04-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210406_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsappprofile',
            name='show_new_responses',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postsappprofile',
            name='show_top_posts',
            field=models.BooleanField(default=True),
        ),
    ]
