# Generated by Django 3.1.7 on 2021-04-07 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_auto_20210331_1623'),
        ('members', '0015_auto_20201228_2048'),
        ('documentation', '0020_auto_20210331_1623'),
        ('objects', '0014_auto_20201115_1955'),
        ('music', '0006_musicappprofile_musicpagesection'),
        ('posts', '0011_auto_20210407_2331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='ReportPost',
        ),
    ]
