# Generated by Django 3.1.7 on 2021-04-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20210408_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='postspagesection',
            name='members_only',
            field=models.BooleanField(default=False),
        ),
    ]
