# Generated by Django 3.2.15 on 2023-01-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20210507_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsappprofile',
            name='n_responses',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='postsappprofile',
            name='post_list_pagination',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='postsappprofile',
            name='response_list_pagination',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='postsappprofile',
            name='title',
            field=models.CharField(default='Posts', max_length=255),
        ),
    ]
