# Generated by Django 3.1 on 2020-09-24 17:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0012_auto_20200913_2236'),
        ('objects', '0011_auto_20200730_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=False)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=255)),
                ('members_only', models.BooleanField(default=True)),
                ('artist', models.CharField(max_length=128)),
                ('text', models.TextField(blank=True, max_length=65535)),
                ('genre', models.CharField(blank=True, max_length=128)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('order', models.DecimalField(decimal_places=4, max_digits=8)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.image')),
                ('links', models.ManyToManyField(blank=True, to='objects.Link')),
                ('marshmallows', models.ManyToManyField(blank=True, to='members.Marshmallow')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
                ('sound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.sound')),
                ('tags', models.ManyToManyField(blank=True, to='objects.Tag')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.video')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=False)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=255)),
                ('members_only', models.BooleanField(default=True)),
                ('artist', models.CharField(max_length=128)),
                ('text', models.TextField(blank=True, max_length=65535)),
                ('genre', models.CharField(blank=True, max_length=128)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.image')),
                ('links', models.ManyToManyField(blank=True, to='objects.Link')),
                ('marshmallows', models.ManyToManyField(blank=True, to='members.Marshmallow')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
                ('tags', models.ManyToManyField(blank=True, to='objects.Tag')),
                ('tracks', models.ManyToManyField(blank=True, to='music.Track')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
