# Generated by Django 3.1 on 2020-09-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='meta_description',
            field=models.TextField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='meta_description',
            field=models.TextField(blank=True, max_length=155, null=True),
        ),
    ]
