# Generated by Django 3.0.7 on 2020-10-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20200928_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='album',
            name='members_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='track',
            name='members_only',
            field=models.BooleanField(default=False),
        ),
    ]
