# Generated by Django 3.1.7 on 2021-04-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_musicappprofile_musicpagesection'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicpagesection',
            name='members_only',
            field=models.BooleanField(default=False),
        ),
    ]
