#!/bin/bash

project="lookaway"
venv_dir="lookaway-dev-env"
user="lookaway"
group="lookaway"

NAME="$project"
DJANGODIR=/home/$user/$venv_dir/$project
USER=$user
GROUP=$group
WORKERS=4
BIND=unix:/home/$user/$venv_dir/lookaway/gunicorn.sock
TIMEOUT=43200
DJANGO_SETTINGS_MODULE=lookaway.settings
DJANGO_WSGI_MODULE=lookaway.wsgi
LOGLEVEL=error

cd /home/$user
source .profile
source $venv_dir/bin/activate

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

exec $venv_dir/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
        --name $NAME \
        --workers $WORKERS \
        --user=$USER \
        --group=$GROUP \
        --bind=$BIND \
        --timeout=$TIMEOUT
        --log-level=$LOGLEVEL \
        --log-file=-
