#!/bin/bash

project=lookaway
venv_dir=lookaway_env
user=lookaway
group=lookaway

NAME="$project"
DJANGODIR=/home/$user/$venv_dir/$project
USER=$user
GROUP=$group
WORKERS=3
BIND=unix:/home/$user/$venv_dir/$project/run/gunicorn.sock
DJANGO_SETTINGS_MODULE=wells.settings
DJANGO_WSGI_MODULE=wells.wsgi
LOGLEVEL=error

cd /home/$user
source $venv_dir/bin/activate

export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

exec $venv_dir/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
        --name $NAME \
        --workers $WORKERS \
        --user=$USER \
        --group=$GROUP \
        --bind=$BIND \
        --log-level=$LOGLEVEL \
        --log-file=-
