# Generated by Django 3.0.7 on 2020-11-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visual',
            name='dimensions',
            field=models.CharField(blank=True, max_length=1028),
        ),
    ]
