# Generated by Django 3.0.7 on 2020-12-13 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_visual_dimensions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visual',
            options={'ordering': ('order',)},
        ),
    ]
