# Generated by Django 3.1.7 on 2021-04-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_auto_20210331_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpagesection',
            name='members_only',
            field=models.BooleanField(default=False),
        ),
    ]
