# Generated by Django 3.2 on 2021-04-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_artpagesection_members_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='order',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
    ]
