# Generated by Django 3.2 on 2021-04-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_gallery_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpagesection',
            name='order',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8),
        ),
    ]
