# Generated by Django 3.2.15 on 2023-01-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0007_alter_artpagesection_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'galleries'},
        ),
        migrations.AlterField(
            model_name='artappprofile',
            name='gallery_list_pagination',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='artappprofile',
            name='n_visuals',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='artappprofile',
            name='title',
            field=models.CharField(default='Art & Photo', max_length=255),
        ),
        migrations.AlterField(
            model_name='artappprofile',
            name='visual_list_pagination',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
