# Generated by Django 3.0.7 on 2020-08-03 18:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0011_auto_20200730_1355'),
        ('members', '0006_profile_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=False)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('numbered', models.BooleanField(default=False)),
                ('intro', models.TextField(max_length=2048)),
                ('outro', models.TextField(max_length=2048)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.Image')),
                ('links', models.ManyToManyField(blank=True, to='objects.Link')),
                ('marshmallows', models.ManyToManyField(blank=True, to='members.Marshmallow')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Member')),
                ('tags', models.ManyToManyField(blank=True, to='objects.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=False)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.DecimalField(decimal_places=4, max_digits=8)),
                ('text', models.TextField(max_length=2048)),
                ('code', models.ManyToManyField(blank=True, to='objects.Code')),
                ('images', models.ManyToManyField(blank=True, to='objects.Image')),
                ('links', models.ManyToManyField(blank=True, to='objects.Link')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Member')),
                ('sounds', models.ManyToManyField(blank=True, to='objects.Sound')),
                ('support_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.SupportDocument')),
                ('tags', models.ManyToManyField(blank=True, to='objects.Tag')),
                ('video', models.ManyToManyField(blank=True, to='objects.Video')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
