# Generated by Django 3.0.7 on 2020-08-03 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='video',
            new_name='videos',
        ),
        migrations.AddField(
            model_name='supportdocument',
            name='title',
            field=models.CharField(default='untitled', max_length=64),
            preserve_default=False,
        ),
    ]
