# Generated by Django 3.0.7 on 2020-08-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_auto_20200803_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='title',
            field=models.CharField(default='untitled', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportdocument',
            name='slug',
            field=models.SlugField(default='untitled'),
            preserve_default=False,
        ),
    ]
