# Generated by Django 3.0.7 on 2020-08-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0004_auto_20200823_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='text',
            field=models.TextField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='supportdocument',
            name='intro',
            field=models.TextField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='supportdocument',
            name='outro',
            field=models.TextField(max_length=65535),
        ),
        migrations.AlterField(
            model_name='supportdocument',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
