# Generated by Django 3.1 on 2020-09-13 22:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20200913_2236'),
        ('objects', '0011_auto_20200730_1355'),
        ('documentation', '0005_auto_20200825_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=False)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('intro', models.TextField(max_length=65535)),
                ('outro', models.TextField(max_length=65535)),
                ('meta_description', models.TextField(blank=True, max_length=155, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.image')),
                ('links', models.ManyToManyField(blank=True, to='objects.Link')),
                ('marshmallows', models.ManyToManyField(blank=True, to='members.Marshmallow')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
                ('tags', models.ManyToManyField(blank=True, to='objects.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Section',
            new_name='SupportDocSection',
        ),
        migrations.AddField(
            model_name='supportdocument',
            name='tip',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
        migrations.AddField(
            model_name='supportdocument',
            name='warning',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
        migrations.CreateModel(
            name='DocumentSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=False)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.DecimalField(decimal_places=4, max_digits=8)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(max_length=65535)),
                ('code', models.ManyToManyField(blank=True, to='objects.Code')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_doc', to='documentation.document')),
                ('images', models.ManyToManyField(blank=True, to='objects.Image')),
                ('links', models.ManyToManyField(blank=True, to='objects.Link')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
                ('sounds', models.ManyToManyField(blank=True, to='objects.Sound')),
                ('tags', models.ManyToManyField(blank=True, to='objects.Tag')),
                ('videos', models.ManyToManyField(blank=True, to='objects.Video')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
