# Generated by Django 3.0.7 on 2020-10-13 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0007_auto_20200928_1714'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentsection',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='supportdocsection',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='supportdocument',
            name='tip',
        ),
        migrations.RemoveField(
            model_name='supportdocument',
            name='warning',
        ),
        migrations.AddField(
            model_name='supportdocsection',
            name='tip',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
        migrations.AddField(
            model_name='supportdocsection',
            name='warning',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='intro',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='outro',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
        migrations.AlterField(
            model_name='documentsection',
            name='text',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
        migrations.AlterField(
            model_name='supportdocsection',
            name='text',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
        migrations.AlterField(
            model_name='supportdocument',
            name='intro',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
        migrations.AlterField(
            model_name='supportdocument',
            name='outro',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
    ]
