# Generated by Django 3.0.7 on 2020-11-15 19:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0014_auto_20201115_1955'),
        ('members', '0014_profile_display_name'),
        ('documentation', '0009_auto_20201013_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=False)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('intro', models.TextField(blank=True, max_length=65535, null=True)),
                ('outro', models.TextField(blank=True, max_length=65535, null=True)),
                ('meta_description', models.TextField(blank=True, max_length=155, null=True)),
                ('is_fiction', models.BooleanField(default=True)),
                ('author', models.CharField(max_length=255)),
                ('original_publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('original_publication_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('audio_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.Sound')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='objects.Image')),
                ('links', models.ManyToManyField(blank=True, to='objects.Link')),
                ('marshmallows', models.ManyToManyField(blank=True, to='members.Marshmallow')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Member')),
                ('tags', models.ManyToManyField(blank=True, to='objects.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='articlesection',
            name='hide_title',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportdocsection',
            name='hide_title',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StorySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=False)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.DecimalField(decimal_places=4, max_digits=8)),
                ('hide_title', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, max_length=65535, null=True)),
                ('code', models.ManyToManyField(blank=True, to='objects.Code')),
                ('images', models.ManyToManyField(blank=True, to='objects.Image')),
                ('links', models.ManyToManyField(blank=True, to='objects.Link')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Member')),
                ('sounds', models.ManyToManyField(blank=True, to='objects.Sound')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_story', to='documentation.Story')),
                ('tags', models.ManyToManyField(blank=True, to='objects.Tag')),
                ('videos', models.ManyToManyField(blank=True, to='objects.Video')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
