# Generated by Django 3.0.7 on 2021-03-11 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_auto_20210109_2203'),
        ('documentation', '0011_auto_20201117_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bitcoin_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crypto.BitcoinWallet'),
        ),
        migrations.AddField(
            model_name='article',
            name='litecoin_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crypto.LitecoinWallet'),
        ),
        migrations.AddField(
            model_name='story',
            name='bitcoin_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crypto.BitcoinWallet'),
        ),
        migrations.AddField(
            model_name='story',
            name='litecoin_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crypto.LitecoinWallet'),
        ),
        migrations.AddField(
            model_name='supportdocument',
            name='bitcoin_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crypto.BitcoinWallet'),
        ),
        migrations.AddField(
            model_name='supportdocument',
            name='litecoin_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crypto.LitecoinWallet'),
        ),
    ]
