# Generated by Django 3.0.7 on 2021-03-12 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0014_auto_20201115_1955'),
        ('documentation', '0012_auto_20210311_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationAppProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meta_description', models.TextField(blank=True, max_length=155, null=True)),
                ('text', models.TextField(blank=True, max_length=65535, null=True)),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_banner', to='objects.Image')),
                ('bg_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_bg_image', to='objects.Image')),
                ('links', models.ManyToManyField(blank=True, to='objects.Link')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_logo', to='objects.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
