# Generated by Django 3.0.7 on 2021-03-24 00:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0014_auto_20201115_1955'),
        ('members', '0015_auto_20201228_2048'),
        ('documentation', '0013_documentationappprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationappprofile',
            name='title',
            field=models.CharField(default='Lookaway CMS', max_length=255),
        ),
        migrations.CreateModel(
            name='DocumentationAppSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=False)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.DecimalField(decimal_places=4, max_digits=8)),
                ('hide_title', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, max_length=65535, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('articles', models.ManyToManyField(blank=True, to='documentation.Article')),
                ('code', models.ManyToManyField(blank=True, to='objects.Code')),
                ('images', models.ManyToManyField(blank=True, to='objects.Image')),
                ('links', models.ManyToManyField(blank=True, to='objects.Link')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Member')),
                ('sounds', models.ManyToManyField(blank=True, to='objects.Sound')),
                ('stories', models.ManyToManyField(blank=True, to='documentation.Story')),
                ('support_documents', models.ManyToManyField(blank=True, to='documentation.SupportDocument')),
                ('tags', models.ManyToManyField(blank=True, to='objects.Tag')),
                ('videos', models.ManyToManyField(blank=True, to='objects.Video')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
