# Generated by Django 3.0.7 on 2021-03-24 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20201228_2048'),
        ('objects', '0014_auto_20201115_1955'),
        ('documentation', '0014_auto_20210324_0047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DocumentationAppSection',
            new_name='DocumentationPageSection',
        ),
    ]
