# Generated by Django 3.0.7 on 2021-03-24 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_auto_20210109_2203'),
        ('documentation', '0015_auto_20210324_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationappprofile',
            name='bitcoin_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crypto.BitcoinWallet'),
        ),
        migrations.AddField(
            model_name='documentationappprofile',
            name='litecoin_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crypto.LitecoinWallet'),
        ),
    ]
