# Generated by Django 3.0.7 on 2021-03-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0016_auto_20210324_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationpagesection',
            name='alert',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
        migrations.AddField(
            model_name='documentationpagesection',
            name='info',
            field=models.TextField(blank=True, max_length=65535, null=True),
        ),
    ]
