# Generated by Django 3.1.7 on 2021-03-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0018_auto_20210329_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentationpagesection',
            options={'ordering': ['order'], 'verbose_name': 'Landing Page Section', 'verbose_name_plural': 'Landing Page Sections'},
        ),
        migrations.AddField(
            model_name='documentationappprofile',
            name='list_pagination',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='documentationappprofile',
            name='n',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='documentationappprofile',
            name='show_new_articles',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentationappprofile',
            name='show_new_stories',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentationappprofile',
            name='show_new_support_documents',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentationappprofile',
            name='show_top_articles',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentationappprofile',
            name='show_top_stories',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documentationappprofile',
            name='show_top_support_documents',
            field=models.BooleanField(default=True),
        ),
    ]
