# Generated by Django 3.1.7 on 2021-03-31 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0014_auto_20201115_1955'),
        ('documentation', '0019_auto_20210330_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationappprofile',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentation_banner', to='objects.image'),
        ),
        migrations.AlterField(
            model_name='documentationappprofile',
            name='bg_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentation_bg_image', to='objects.image'),
        ),
        migrations.AlterField(
            model_name='documentationappprofile',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentation_logo', to='objects.image'),
        ),
    ]
