# Generated by Django 3.1.7 on 2021-04-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0020_auto_20210331_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlesection',
            name='members_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentationpagesection',
            name='members_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storysection',
            name='members_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportdocsection',
            name='members_only',
            field=models.BooleanField(default=False),
        ),
    ]
