# Generated by Django 3.2.15 on 2023-01-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0023_auto_20210428_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentationappprofile',
            name='list_pagination',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='documentationappprofile',
            name='title',
            field=models.CharField(default='Zine', max_length=255),
        ),
    ]
