# Generated by Django 3.1.7 on 2021-04-13 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0014_auto_20201115_1955'),
        ('crypto', '0006_auto_20210109_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAppProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Lookaway CMS', max_length=255)),
                ('show_title', models.BooleanField(default=True)),
                ('meta_description', models.TextField(blank=True, max_length=155, null=True)),
                ('show_desc', models.BooleanField(default=True)),
                ('text', models.TextField(blank=True, max_length=65535, null=True)),
                ('nav_posts_name', models.CharField(max_length=64)),
                ('nav_documentation_name', models.CharField(max_length=64)),
                ('nav_art_name', models.CharField(max_length=64)),
                ('nav_music_name', models.CharField(max_length=64)),
                ('n_posts', models.PositiveIntegerField(default=5)),
                ('n_responses', models.PositiveIntegerField(default=5)),
                ('show_new_posts', models.BooleanField(default=True)),
                ('show_top_posts', models.BooleanField(default=True)),
                ('show_new_responses', models.BooleanField(default=False)),
                ('show_top_responses', models.BooleanField(default=False)),
                ('n_articles', models.PositiveIntegerField(default=5)),
                ('n_stories', models.PositiveIntegerField(default=5)),
                ('n_documents', models.PositiveIntegerField(default=5)),
                ('show_new_articles', models.BooleanField(default=True)),
                ('show_top_articles', models.BooleanField(default=True)),
                ('show_new_stories', models.BooleanField(default=True)),
                ('show_top_stories', models.BooleanField(default=True)),
                ('show_new_documents', models.BooleanField(default=True)),
                ('show_top_documents', models.BooleanField(default=True)),
                ('n_visuals', models.PositiveIntegerField(default=25)),
                ('n_galleries', models.PositiveIntegerField(default=5)),
                ('show_new_visuals', models.BooleanField(default=True)),
                ('show_top_visual', models.BooleanField(default=True)),
                ('show_new_galleries', models.BooleanField(default=True)),
                ('show_top_galleries', models.BooleanField(default=True)),
                ('n_tracks', models.PositiveIntegerField(default=5)),
                ('n_albums', models.PositiveIntegerField(default=5)),
                ('show_new_tracks', models.BooleanField(default=True)),
                ('show_top_tracks', models.BooleanField(default=True)),
                ('show_new_albums', models.BooleanField(default=True)),
                ('show_top_albums', models.BooleanField(default=True)),
                ('n_tags', models.PositiveIntegerField(default=50)),
                ('show_tags', models.BooleanField(default=True)),
                ('legal_notice', models.TextField(blank=True, max_length=2048, null=True)),
                ('admin_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('css_path', models.CharField(blank=True, max_length=2048, null=True)),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_banner', to='objects.image')),
                ('bg_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_bg_image', to='objects.image')),
                ('bitcoin_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crypto.bitcoinwallet')),
                ('links', models.ManyToManyField(blank=True, to='objects.Link')),
                ('litecoin_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crypto.litecoinwallet')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_logo', to='objects.image')),
                ('nav_art_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_art_image', to='objects.image')),
                ('nav_documentation_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_documentation_image', to='objects.image')),
                ('nav_music_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_music_image', to='objects.image')),
                ('nav_posts_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_posts_image', to='objects.image')),
            ],
            options={
                'verbose_name': 'Home App Profile',
            },
        ),
    ]
