# Generated by Django 3.2 on 2021-04-14 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210414_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeappprofile',
            old_name='show_top_visual',
            new_name='show_top_visuals',
        ),
    ]
