# Generated by Django 3.2 on 2021-04-21 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0014_auto_20201115_1955'),
        ('home', '0004_rename_show_top_visual_homeappprofile_show_top_visuals'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeappprofile',
            name='nav_members_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_members_image', to='objects.image'),
        ),
        migrations.AddField(
            model_name='homeappprofile',
            name='nav_members_name',
            field=models.CharField(default='members', max_length=64),
        ),
    ]
