# Generated by Django 3.2 on 2021-04-22 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210421_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeappprofile',
            name='nav_show_art',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homeappprofile',
            name='nav_show_documentation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homeappprofile',
            name='nav_show_members',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homeappprofile',
            name='nav_show_music',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homeappprofile',
            name='nav_show_posts',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='homeappprofile',
            name='nav_art_name',
            field=models.CharField(default='Art', max_length=64),
        ),
        migrations.AlterField(
            model_name='homeappprofile',
            name='nav_documentation_name',
            field=models.CharField(default='Zine', max_length=64),
        ),
        migrations.AlterField(
            model_name='homeappprofile',
            name='nav_members_name',
            field=models.CharField(default='Members', max_length=64),
        ),
        migrations.AlterField(
            model_name='homeappprofile',
            name='nav_music_name',
            field=models.CharField(default='Music', max_length=64),
        ),
        migrations.AlterField(
            model_name='homeappprofile',
            name='nav_posts_name',
            field=models.CharField(default='Posts', max_length=64),
        ),
    ]
