# Generated by Django 3.2 on 2021-05-06 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0018_auto_20210428_1522'),
        ('home', '0007_alter_homepagesection_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeappprofile',
            name='nav_objects_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nav_objects_image', to='objects.image'),
        ),
        migrations.AddField(
            model_name='homeappprofile',
            name='nav_objects_name',
            field=models.CharField(default='Objects', max_length=64),
        ),
        migrations.AddField(
            model_name='homeappprofile',
            name='nav_show_objects',
            field=models.BooleanField(default=True),
        ),
    ]
