# Generated by Django 3.0.7 on 2020-07-03 17:54

from django.db import migrations, models
import objects.models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_auto_20200629_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(max_length=255, upload_to=objects.models.member_image_dir),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumbnail_file',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=objects.models.member_thumbnail_dir),
        ),
        migrations.AlterField(
            model_name='sound',
            name='sound_file',
            field=models.FileField(max_length=256, upload_to=objects.models.member_sound_dir),
        ),
    ]
