# Generated by Django 3.0.7 on 2020-07-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0003_auto_20200703_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sound',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AddField(
            model_name='code',
            name='md5',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
