# Generated by Django 3.0.7 on 2020-07-14 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0004_auto_20200706_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='source_url',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='favicon_href',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
