# Generated by Django 3.0.7 on 2020-07-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_auto_20200714_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='image',
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
