# Generated by Django 3.0.7 on 2020-07-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0006_auto_20200716_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='key',
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('key', 'value'), name='key-value pair'),
        ),
    ]
