# Generated by Django 3.0.7 on 2020-07-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0007_auto_20200717_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='value',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
