# Generated by Django 3.0.7 on 2020-07-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0008_auto_20200717_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='testing'),
            preserve_default=False,
        ),
    ]
