# Generated by Django 3.0.7 on 2020-07-29 20:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import objects.models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_profile_text'),
        ('objects', '0009_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=False)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('video_file', models.FileField(max_length=256, upload_to=objects.models.member_video_dir)),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField(blank=True, max_length=1024, null=True)),
                ('credit', models.CharField(blank=True, max_length=256, null=True)),
                ('marshmallows', models.ManyToManyField(blank=True, to='members.Marshmallow')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Member')),
                ('tags', models.ManyToManyField(blank=True, to='objects.Tag')),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
