# Generated by Django 3.0.7 on 2020-07-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_profile_text'),
        ('objects', '0010_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='marshmallows',
            field=models.ManyToManyField(blank=True, to='members.Marshmallow'),
        ),
        migrations.AddField(
            model_name='tag',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
