# Generated by Django 3.0.7 on 2020-10-14 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0012_auto_20200928_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='text',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.TextField(max_length=65535),
        ),
    ]
