# Generated by Django 3.0.7 on 2020-11-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0013_auto_20201014_2358'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
    ]
