# Generated by Django 3.2 on 2021-04-26 19:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_alter_member_options'),
        ('crypto', '0007_auto_20210426_1841'),
        ('objects', '0015_auto_20210426_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectsPageSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=False)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.DecimalField(decimal_places=4, max_digits=8)),
                ('hide_title', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, max_length=65535, null=True)),
                ('info', models.TextField(blank=True, max_length=65535, null=True)),
                ('alert', models.TextField(blank=True, max_length=65535, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('members_only', models.BooleanField(default=False)),
                ('code', models.ManyToManyField(blank=True, to='objects.Code')),
                ('codes', models.ManyToManyField(blank=True, related_name='section_codes', to='objects.Code')),
                ('images', models.ManyToManyField(blank=True, related_name='section_images', to='objects.Image')),
                ('links', models.ManyToManyField(blank=True, related_name='section_links', to='objects.Link')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
                ('sounds', models.ManyToManyField(blank=True, related_name='section_sounds', to='objects.Sound')),
                ('tags', models.ManyToManyField(blank=True, to='objects.Tag')),
                ('videos', models.ManyToManyField(blank=True, related_name='section_videos', to='objects.Video')),
            ],
            options={
                'verbose_name': 'Landing Page Section',
                'verbose_name_plural': 'Landing Page Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ObjectsAppProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Lookaway CMS', max_length=255)),
                ('show_title', models.BooleanField(default=True)),
                ('meta_description', models.TextField(blank=True, max_length=155, null=True)),
                ('show_desc', models.BooleanField(default=True)),
                ('text', models.TextField(blank=True, max_length=65535, null=True)),
                ('show_images', models.BooleanField(default=True)),
                ('show_sounds', models.BooleanField(default=True)),
                ('show_videos', models.BooleanField(default=True)),
                ('show_codes', models.BooleanField(default=True)),
                ('show_links', models.BooleanField(default=True)),
                ('n_images', models.PositiveIntegerField(default=10)),
                ('n_sounds', models.PositiveIntegerField(default=10)),
                ('n_videos', models.PositiveIntegerField(default=10)),
                ('n_codes', models.PositiveIntegerField(default=10)),
                ('n_links', models.PositiveIntegerField(default=10)),
                ('images_list_pagination', models.PositiveIntegerField(default=25)),
                ('sounds_list_pagination', models.PositiveIntegerField(default=10)),
                ('videos_list_pagination', models.PositiveIntegerField(default=10)),
                ('codes_list_pagination', models.PositiveIntegerField(default=10)),
                ('links_list_pagination', models.PositiveIntegerField(default=10)),
                ('ffmpeg_path', models.CharField(max_length=64)),
                ('image_max_height', models.PositiveIntegerField(default=2500)),
                ('image_max_width', models.PositiveIntegerField(default=2500)),
                ('thumbnail_max_height', models.PositiveIntegerField(default=250)),
                ('thumbnail_max_width', models.PositiveIntegerField(default=250)),
                ('image_format', models.CharField(max_length=4)),
                ('sound_format', models.CharField(max_length=4)),
                ('video_format', models.CharField(max_length=4)),
                ('sound_bitrate', models.PositiveIntegerField(default=1000)),
                ('video_bitrate', models.PositiveIntegerField(default=1000)),
                ('sound_crf', models.PositiveIntegerField(default=250)),
                ('sound_qmin', models.PositiveIntegerField(default=250)),
                ('sound_qmax', models.PositiveIntegerField(default=250)),
                ('video_crf', models.PositiveIntegerField(default=250)),
                ('video_qmin', models.PositiveIntegerField(default=250)),
                ('video_qmax', models.PositiveIntegerField(default=250)),
                ('banner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objects_banner', to='objects.image')),
                ('bg_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objects_bg_image', to='objects.image')),
                ('bitcoin_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crypto.bitcoinwallet')),
                ('links', models.ManyToManyField(blank=True, to='objects.Link')),
                ('litecoin_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crypto.litecoinwallet')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objects_logo', to='objects.image')),
            ],
            options={
                'verbose_name': 'App Profile',
            },
        ),
    ]
