# Generated by Django 3.2 on 2021-04-27 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0016_objectsappprofile_objectspagesection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsappprofile',
            name='ffmpeg_path',
            field=models.CharField(default='/usr/bin/ffmpeg', max_length=64),
        ),
        migrations.AlterField(
            model_name='objectsappprofile',
            name='sound_bitrate',
            field=models.PositiveIntegerField(default=320),
        ),
        migrations.AlterField(
            model_name='objectsappprofile',
            name='video_bitrate',
            field=models.PositiveIntegerField(default=2048),
        ),
    ]
