# Generated by Django 3.2.15 on 2023-01-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0018_auto_20210428_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'ordering': ['order', 'title', 'language']},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='sound',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='objectsappprofile',
            name='n_codes',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='objectsappprofile',
            name='n_images',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='objectsappprofile',
            name='n_links',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='objectsappprofile',
            name='n_sounds',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='objectsappprofile',
            name='n_videos',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='objectsappprofile',
            name='title',
            field=models.CharField(default='Multimedia', max_length=255),
        ),
    ]
