# Generated by Django 3.0.7 on 2020-12-28 20:48

import crypto.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0014_auto_20201115_1955'),
        ('members', '0015_auto_20201228_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='LitecoinWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=False)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField(blank=True, max_length=1024, null=True)),
                ('public_address', models.CharField(max_length=64)),
                ('qr_code_lg', models.ImageField(max_length=255, upload_to=crypto.models.member_crypto_dir)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Member')),
                ('tags', models.ManyToManyField(blank=True, to='objects.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BitcoinWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=False)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField(blank=True, max_length=1024, null=True)),
                ('public_address', models.CharField(max_length=64)),
                ('qr_code_lg', models.ImageField(max_length=255, upload_to=crypto.models.member_crypto_dir)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.Member')),
                ('tags', models.ManyToManyField(blank=True, to='objects.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
