# Generated by Django 3.0.7 on 2020-12-28 22:15

import crypto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoinwallet',
            name='qr_code_lg',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=crypto.models.member_crypto_dir),
        ),
        migrations.AlterField(
            model_name='litecoinwallet',
            name='qr_code_lg',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=crypto.models.member_crypto_dir),
        ),
    ]
