# Generated by Django 3.0.7 on 2021-01-08 23:15
import uuid

from django.db import migrations

def gen_uuid(apps, schema_editor):

    BitcoinWallets = apps.get_model('crypto', 'BitcoinWallet')

    for row in BitcoinWallets.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['public_address'])

    LitecoinWallets = apps.get_model('crypto', 'LitecoinWallet')

    for row in LitecoinWallets.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['public_address'])

class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_auto_20210108_2314'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid),
    ]
