# Generated by Django 3.0.7 on 2021-01-08 23:15
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_auto_20210108_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='BitcoinWallet',
            name='public_address',
            field=models.UUIDField(
                default=uuid.uuid4,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name='LitecoinWallet',
            name='public_address',
            field=models.UUIDField(
                default=uuid.uuid4,
                unique=True,
            ),
        ),
    ]

