# Generated by Django 3.0.7 on 2021-01-09 22:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_auto_20210108_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoinwallet',
            name='public_address',
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='litecoinwallet',
            name='public_address',
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True),
        ),
    ]
