# Generated by Django 3.0.7 on 2020-07-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='media_capacity',
            field=models.PositiveIntegerField(default=5000000),
        ),
    ]
