# Generated by Django 3.0.7 on 2020-07-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20200727_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
