# Generated by Django 3.0.7 on 2020-08-16 16:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_profile_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32)),
                ('expiration_date', models.DateTimeField(default=datetime.datetime(2020, 8, 23, 16, 2, 32, 52636, tzinfo=utc))),
                ('label', models.CharField(max_length=64, unique=True)),
                ('note', models.TextField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
