# Generated by Django 3.0.7 on 2020-08-23 21:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_invitelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 30, 21, 29, 52, 27225, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='slug',
            field=models.SlugField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='media_capacity',
            field=models.PositiveIntegerField(default=10000000000),
        ),
    ]
