# Generated by Django 3.0.7 on 2020-08-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20200824_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='media_capacity',
            field=models.BigIntegerField(default=10000000000),
        ),
    ]
