# Generated by Django 3.0.7 on 2020-08-24 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20200824_2250'),
        ('members', '0010_auto_20200824_2336'),
    ]

    operations = [
    ]
