# Generated by Django 3.1 on 2020-09-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_merge_20200824_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='media_capacity',
            field=models.BigIntegerField(default=4000000000),
        ),
    ]
