# Generated by Django 3.0.7 on 2020-12-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='media_capacity',
            field=models.BigIntegerField(default=2000000000),
        ),
    ]
