# Generated by Django 3.1.7 on 2021-04-12 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_auto_20210109_2203'),
        ('members', '0015_auto_20201228_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bitcoin_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crypto.bitcoinwallet'),
        ),
        migrations.AddField(
            model_name='profile',
            name='litecoin_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crypto.litecoinwallet'),
        ),
    ]
