# Generated by Django 3.1.7 on 2021-04-12 20:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_postspagesection_members_only'),
        ('objects', '0014_auto_20201115_1955'),
        ('art', '0005_artpagesection_members_only'),
        ('music', '0008_auto_20210412_1456'),
        ('documentation', '0021_auto_20210409_1625'),
        ('members', '0016_auto_20210412_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_marshmallow_allocation',
            new_name='last_marshmallow_time',
        ),
        migrations.AddField(
            model_name='profile',
            name='album_list_pagination',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='article_list_pagination',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_banner', to='objects.image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='bg_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_bg_image', to='objects.image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='document_list_pagination',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='gallery_list_pagination',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_post_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_report_post_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_response_post_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='links',
            field=models.ManyToManyField(blank=True, to='objects.Link'),
        ),
        migrations.AddField(
            model_name='profile',
            name='meta_description',
            field=models.TextField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='n_albums',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='n_articles',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='n_documents',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='n_galleries',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='n_posts',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='n_responses',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='n_stories',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='n_tracks',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='n_visuals',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='profile',
            name='post_list_pagination',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='response_list_pagination',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_desc',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_new_albums',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_new_articles',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_new_documents',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_new_galleries',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_new_posts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_new_responses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_new_stories',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_new_tracks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_new_visuals',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_title',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_top_albums',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_top_articles',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_top_documents',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_top_galleries',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_top_posts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_top_responses',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_top_stories',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_top_tracks',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_top_visual',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='story_list_pagination',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(default='Lookaway CMS', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='track_list_pagination',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='visual_list_pagination',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.CreateModel(
            name='MemberProfileSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=False)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('order', models.DecimalField(decimal_places=4, max_digits=8)),
                ('hide_title', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, max_length=65535, null=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('members_only', models.BooleanField(default=False)),
                ('albums', models.ManyToManyField(blank=True, to='music.Album')),
                ('articles', models.ManyToManyField(blank=True, to='documentation.Article')),
                ('code', models.ManyToManyField(blank=True, to='objects.Code')),
                ('documents', models.ManyToManyField(blank=True, to='documentation.SupportDocument')),
                ('galleries', models.ManyToManyField(blank=True, to='art.Gallery')),
                ('images', models.ManyToManyField(blank=True, to='objects.Image')),
                ('links', models.ManyToManyField(blank=True, to='objects.Link')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
                ('posts', models.ManyToManyField(blank=True, to='posts.Post')),
                ('responses', models.ManyToManyField(blank=True, to='posts.ResponsePost')),
                ('sounds', models.ManyToManyField(blank=True, to='objects.Sound')),
                ('story', models.ManyToManyField(blank=True, to='documentation.Story')),
                ('tags', models.ManyToManyField(blank=True, to='objects.Tag')),
                ('tracks', models.ManyToManyField(blank=True, to='music.Track')),
                ('videos', models.ManyToManyField(blank=True, to='objects.Video')),
                ('visuals', models.ManyToManyField(blank=True, to='art.Visual')),
            ],
            options={
                'verbose_name': 'Member Page Section',
                'verbose_name_plural': 'Member Page Sections',
                'ordering': ['order'],
            },
        ),
    ]
