# Generated by Django 3.1.7 on 2021-04-14 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_auto_20210109_2203'),
        ('members', '0020_membersappprofile_memberspagesection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membersappprofile',
            old_name='n_contributor_models',
            new_name='n_contributors',
        ),
        migrations.RenameField(
            model_name='membersappprofile',
            old_name='n_members_models',
            new_name='n_members',
        ),
        migrations.AddField(
            model_name='membersappprofile',
            name='bitcoin_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crypto.bitcoinwallet'),
        ),
        migrations.AddField(
            model_name='membersappprofile',
            name='litecoin_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crypto.litecoinwallet'),
        ),
    ]
