# Generated by Django 3.2 on 2021-04-23 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_auto_20210414_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='show_top_visual',
            new_name='show_top_visuals',
        ),
    ]
