# Generated by Django 3.2.15 on 2023-01-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_auto_20210428_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersappprofile',
            name='members_list_pagination',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='membersappprofile',
            name='title',
            field=models.CharField(default='Members', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(default='Lookaway Information', max_length=255),
        ),
    ]
