from django.urls import path
import documentation.views as views

app_name= "documentation"

urlpatterns = [
    # Read Views
    path(
        '', 
        views.DocumentationPageView.as_view(),
        name='documentation_page',
    ),
    path(
        'articles/new/', 
        views.ArticleListView.as_view(),
        name='new_articles',
    ),
    path(
        'articles', 
        views.TopArticleListView.as_view(),
        name='top_articles',
    ),
    path(
        'articles/<slug:slug>/', 
        views.ArticleDetailView.as_view(),
        name='article_detail',
    ),
    path(
        'article-section/<int:pk>/', 
        views.ArticleSectionDetailView.as_view(),
        name='article_section_detail',
    ),
    path(
        'stories/new/', 
        views.StoryListView.as_view(),
        name='new_stories',
    ),
    path(
        'stories/', 
        views.TopStoryListView.as_view(),
        name='top_stories',
    ),
    path(
        'stories/<slug:slug>/', 
        views.StoryDetailView.as_view(),
        name='story_detail',
    ),
    path(
        'stories/story-section/<int:pk>/', 
        views.StorySectionDetailView.as_view(),
        name='story_section_detail',
    ),
    path(
        'information/new', 
        views.SupportDocumentListView.as_view(),
        name='new_support_documents',
    ),
    path(
        'information/', 
        views.TopSupportDocumentListView.as_view(),
        name='top_support_documents',
    ),
    path(
        'information/<slug:slug>/', 
        views.SupportDocumentDetailView.as_view(),
        name='support_document_detail',
    ),
    path(
        'support-doc-section/<int:pk>/', 
        views.SupportDocSectionDetailView.as_view(),
        name='support_doc_section_detail',
    ),
    # Member Specific Views
    path(
        'member/<slug:member>/articles/', 
        views.MemberArticleView.as_view(),
        name='member_articles',
    ),
    path(
        'member/<slug:member>/article-sections/', 
        views.MemberArticleSectionView.as_view(),
        name='member_article_sections',
    ),
    path(
        'member/<slug:member>/stories/', 
        views.MemberStoryView.as_view(),
        name='member_stories',
    ),
    path(
        'member/<slug:member>/story-sections/', 
        views.MemberStorySectionView.as_view(),
        name='member_story_sections',
    ),
    path(
        'member/<slug:member>/information/', 
        views.MemberSupportDocumentView.as_view(),
        name='member_support_documents',
    ),
    path(
        'member/<slug:member>/support-doc-sections/', 
        views.MemberSupportDocSectionView.as_view(),
        name='member_support_doc_sections',
    ),
    # Create Views
    path(
        'add/article/', 
        views.ArticleCreateView.as_view(),
        name='article_create',
    ),
    path(
        'add/article-section/', 
        views.ArticleSectionCreateView.as_view(),
        name='article_section_create',
    ),
    path(
        'add/story/', 
        views.StoryCreateView.as_view(),
        name='story_create',
    ),
    path(
        'add/story-section/', 
        views.StorySectionCreateView.as_view(),
        name='story_section_create',
    ),
    path(
        'add/support-document/', 
        views.SupportDocumentCreateView.as_view(),
        name='support_document_create',
    ),
    path(
        'add/support-doc-section/', 
        views.SupportDocSectionCreateView.as_view(),
        name='support_doc_section_create',
    ),
    # Update Views
    path(
        'modify/article/<slug:slug>/', 
        views.ArticleUpdateView.as_view(),
        name='article_update',
    ),
    path(
        'modify/article-section/<int:pk>/', 
        views.ArticleSectionUpdateView.as_view(),
        name='article_section_update',
    ),
    path(
        'modify/story/<slug:slug>/', 
        views.StoryUpdateView.as_view(),
        name='story_update',
    ),
    path(
        'modify/story-section/<int:pk>/', 
        views.StorySectionUpdateView.as_view(),
        name='story_section_update',
    ),
    path(
        'modify/support-document/<slug:slug>/', 
        views.SupportDocumentUpdateView.as_view(),
        name='support_document_update',
    ),
    path(
        'modify/support-doc-section/<int:pk>/', 
        views.SupportDocSectionUpdateView.as_view(),
        name='support_doc_section_update',
    ),
    # Delete Views
    path(
        'delete/article/<int:pk>/', 
        views.ArticleDeleteView.as_view(),
        name='article_delete',
    ),
    path(
        'delete/article-section/<int:pk>/', 
        views.ArticleSectionDeleteView.as_view(),
        name='article_section_delete',
    ),
    path(
        'delete/story/<int:pk>/', 
        views.StoryDeleteView.as_view(),
        name='story_delete',
    ),
    path(
        'delete/story-section/<int:pk>/', 
        views.StorySectionDeleteView.as_view(),
        name='story_section_delete',
    ),
    path(
        'delete/support-document/<int:pk>/', 
        views.SupportDocumentDeleteView.as_view(),
        name='support_document_delete',
    ),
    path(
        'delete/support-doc-section/<int:pk>/', 
        views.SupportDocSectionDeleteView.as_view(),
        name='support_doc_section_delete',
    ),
    # Publish Views
    path(
        'publish/article/<int:pk>/', 
        views.publish_article_view,
        name='publish_article',
    ),
    path(
        'publish/story/<int:pk>/', 
        views.publish_story_view,
        name='publish_story',
    ),
    path(
        'publish/support-document/<int:pk>/', 
        views.publish_support_document_view,
        name='publish_support_document',
    ),
    # Marshmallow Views
    path(
        'article/<int:pk>/add-marshmallow', 
        views.add_marshmallow_to_article_view,
        name='article_marshmallow',
    ),
    path(
        'story/<int:pk>/add-marshmallow', 
        views.add_marshmallow_to_article_view,
        name='story_marshmallow',
    ),
    path(
        'support-document/<int:pk>/add-marshmallow', 
        views.add_marshmallow_to_support_document_view,
        name='support_document_marshmallow',
    ),
]
